use crate::{Meta, Result, StockDataFrame};

/// Supported stockstats indicators.
///
/// This enum is used for dispatching computations in [`StockDataFrame::get`],
/// replacing large string-based `match` blocks.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum Indicator {
    Ao,
    Aroon,
    Atr,
    Boll,
    Bop,
    C,
    Cci,
    Change,
    Chop,
    Cmo,
    Coppock,
    Cr,
    Cti,
    D,
    Dma,
    Dx,
    Adx,
    Adxr,
    Ema,
    Eri,
    Eribear,
    Eribull,
    Fc,
    Ftr,
    Ichimoku,
    Inertia,
    Kama,
    Kdjd,
    Kdjj,
    Kdjk,
    Ker,
    Kst,
    LinearWma,
    Lrma,
    Macd,
    Mad,
    Max,
    Mfi,
    Min,
    Mstd,
    Mvar,
    Ndi,
    Ndm,
    P,
    Pdi,
    Pdm,
    Pgo,
    Ppo,
    Psl,
    Pvo,
    Qqe,
    R,
    Roc,
    Rsi,
    Rsv,
    Rvgi,
    Rvgis,
    S,
    Sma,
    Smma,
    Stochrsi,
    Supertrend,
    Tema,
    Tp,
    Trix,
    Tr,
    Vr,
    Vwma,
    Wr,
    Wt,
    Wt1,
    Wt2,
    Z,
}

impl Indicator {
    pub(crate) fn from_name(name: &str) -> Option<Self> {
        Some(match name {
            "ao" => Self::Ao,
            "aroon" => Self::Aroon,
            "atr" => Self::Atr,
            "boll" | "boll_ub" | "boll_lb" => Self::Boll,
            "bop" => Self::Bop,
            "c" => Self::C,
            "cci" => Self::Cci,
            "change" => Self::Change,
            "chop" => Self::Chop,
            "cmo" => Self::Cmo,
            "coppock" => Self::Coppock,
            "cr" => Self::Cr,
            "cti" => Self::Cti,
            "d" => Self::D,
            "dma" => Self::Dma,
            "dx" => Self::Dx,
            "adx" => Self::Adx,
            "adxr" => Self::Adxr,
            "ema" => Self::Ema,
            "eri" => Self::Eri,
            "eribear" => Self::Eribear,
            "eribull" => Self::Eribull,
            "fc" => Self::Fc,
            "ftr" => Self::Ftr,
            "ichimoku" => Self::Ichimoku,
            "inertia" => Self::Inertia,
            "kama" => Self::Kama,
            "kdjd" => Self::Kdjd,
            "kdjj" => Self::Kdjj,
            "kdjk" => Self::Kdjk,
            "ker" => Self::Ker,
            "kst" => Self::Kst,
            "linear_wma" => Self::LinearWma,
            "lrma" | "linear_regression" => Self::Lrma,
            "macd" => Self::Macd,
            "mad" => Self::Mad,
            "max" => Self::Max,
            "mfi" => Self::Mfi,
            "min" => Self::Min,
            "mstd" => Self::Mstd,
            "mvar" => Self::Mvar,
            "ndi" => Self::Ndi,
            "ndm" => Self::Ndm,
            "p" => Self::P,
            "pdi" => Self::Pdi,
            "pdm" => Self::Pdm,
            "pgo" => Self::Pgo,
            "ppo" => Self::Ppo,
            "psl" => Self::Psl,
            "pvo" => Self::Pvo,
            "qqe" => Self::Qqe,
            "r" | "rate" => Self::R,
            "roc" => Self::Roc,
            "rsi" => Self::Rsi,
            "rsv" => Self::Rsv,
            "rvgi" => Self::Rvgi,
            "rvgis" => Self::Rvgis,
            "s" => Self::S,
            "sma" => Self::Sma,
            "smma" => Self::Smma,
            "stochrsi" => Self::Stochrsi,
            "supertrend" => Self::Supertrend,
            "tema" => Self::Tema,
            "tp" | "middle" | "typical_price" => Self::Tp,
            "trix" => Self::Trix,
            "tr" => Self::Tr,
            "vr" => Self::Vr,
            "vwma" => Self::Vwma,
            "wr" => Self::Wr,
            "wt" => Self::Wt,
            "wt1" => Self::Wt1,
            "wt2" => Self::Wt2,
            "z" => Self::Z,
            _ => return None,
        })
    }

    pub(crate) fn default_windows(self) -> Option<&'static str> {
        Some(match self {
            Self::Ao => "5,34",
            Self::Aroon => "25",
            Self::Atr => "14",
            Self::Boll => "20",
            Self::Cci => "14",
            Self::Change => "1",
            Self::Chop => "14",
            Self::Cmo => "14",
            Self::Coppock => "10,11,14",
            Self::Cr => "26",
            Self::Cti => "12",
            Self::Dma => "10,50",
            Self::Eri | Self::Eribear | Self::Eribull => "13",
            Self::Ichimoku => "9,26,52",
            Self::Inertia => "20,14",
            Self::Ftr => "9",
            Self::Kama => "10,5,34",
            Self::Kdjd | Self::Kdjj | Self::Kdjk => "9",
            Self::Ker => "10",
            Self::Macd => "12,26,9",
            Self::Mfi => "14",
            Self::Ndi => "14",
            Self::Pdi => "14",
            Self::Pgo => "14",
            Self::Ppo => "12,26,9",
            Self::Pvo => "12,26,9",
            Self::Psl => "12",
            Self::Qqe => "14,5",
            Self::Roc => "12",
            Self::Rsi => "14",
            Self::Rsv => "9",
            Self::Rvgi | Self::Rvgis => "14",
            Self::Stochrsi => "14",
            Self::Supertrend => "14",
            Self::Tema => "5",
            Self::Trix => "12",
            Self::Wr => "14",
            Self::Wt => "10,21",
            Self::Vr => "26",
            Self::Vwma => "14",
            _ => return None,
        })
    }

    pub(crate) fn default_column(self) -> Option<&'static str> {
        Some(match self {
            Self::Cti => "close",
            Self::Dma => "close",
            Self::Kama => "close",
            Self::Ker => "close",
            Self::Psl => "close",
            Self::Tema => "close",
            Self::Trix => "close",
            Self::Lrma => "close",
            _ => return None,
        })
    }

    pub(crate) fn compute(self, sdf: &mut StockDataFrame, meta: Meta) -> Result<()> {
        match self {
            Self::Change => sdf.get_change(meta),
            Self::R => sdf.get_r(meta),
            Self::S => sdf.get_s(meta),
            Self::D => sdf.get_d(meta),
            Self::C => sdf.get_c(meta),
            Self::Fc => sdf.get_fc(meta),
            Self::Max => sdf.get_max(meta),
            Self::Min => sdf.get_min(meta),
            Self::P => sdf.get_p(meta),
            Self::Sma => sdf.get_sma(meta),
            Self::Smma => sdf.get_smma(meta),
            Self::Ema => sdf.get_ema(meta),
            Self::Macd => sdf.get_macd(meta),
            Self::Rsv => sdf.get_rsv(meta),
            Self::Rsi => sdf.get_rsi(meta),
            Self::Stochrsi => sdf.get_stochrsi(meta),
            Self::Wr => sdf.get_wr(meta),
            Self::Kdjk => sdf.get_kdjk(meta),
            Self::Kdjd => sdf.get_kdjd(meta),
            Self::Kdjj => sdf.get_kdjj(meta),
            Self::Boll => sdf.get_boll(meta.with_name("boll")),
            Self::Tr => sdf.get_tr(meta),
            Self::Atr => sdf.get_atr(meta),
            Self::Dma => sdf.get_dma(meta),
            Self::Pdm => sdf.get_pdm(meta),
            Self::Ndm => sdf.get_ndm(meta),
            Self::Pdi => sdf.get_pdi(meta),
            Self::Ndi => sdf.get_ndi(meta),
            Self::Dx => sdf.get_dx(meta),
            Self::Adx => sdf.get_adx(meta),
            Self::Adxr => sdf.get_adxr(meta),
            Self::Cci => sdf.get_cci(meta),
            Self::Vr => sdf.get_vr(meta),
            Self::Cr => sdf.get_cr(meta),
            Self::Tp => sdf.get_tp(meta),
            Self::Mad => sdf.get_mad(meta),
            Self::Mstd => sdf.get_mstd(meta),
            Self::Mvar => sdf.get_mvar(meta),
            Self::Roc => sdf.get_roc(meta),
            Self::Lrma => sdf.get_lrma(meta),
            Self::LinearWma => sdf.get_linear_wma(meta),
            Self::Cti => sdf.get_cti(meta),
            Self::Trix => sdf.get_trix(meta),
            Self::Tema => sdf.get_tema(meta),
            Self::Mfi => sdf.get_mfi(meta),
            Self::Ker => sdf.get_ker(meta),
            Self::Kama => sdf.get_kama(meta),
            Self::Vwma => sdf.get_vwma(meta),
            Self::Chop => sdf.get_chop(meta),
            Self::Wt => sdf.get_wt(meta),
            Self::Wt1 => sdf.get_wt1(meta),
            Self::Wt2 => sdf.get_wt2(meta),
            Self::Supertrend => sdf.get_supertrend(meta),
            Self::Ao => sdf.get_ao(meta),
            Self::Bop => sdf.get_bop(meta),
            Self::Cmo => sdf.get_cmo(meta),
            Self::Aroon => sdf.get_aroon(meta),
            Self::Z => sdf.get_z(meta),
            Self::Ichimoku => sdf.get_ichimoku(meta),
            Self::Coppock => sdf.get_coppock(meta),
            Self::Pvo => sdf.get_pvo(meta),
            Self::Ppo => sdf.get_ppo(meta),
            Self::Eri => sdf.get_eri(meta),
            Self::Eribull => sdf.get_eribull(meta),
            Self::Eribear => sdf.get_eribear(meta),
            Self::Ftr => sdf.get_ftr(meta),
            Self::Rvgi => sdf.get_rvgi(meta),
            Self::Rvgis => sdf.get_rvgis(meta),
            Self::Inertia => sdf.get_inertia(meta),
            Self::Kst => sdf.get_kst(meta),
            Self::Pgo => sdf.get_pgo(meta),
            Self::Psl => sdf.get_psl(meta),
            Self::Qqe => sdf.get_qqe(meta),
        }
    }
}
